// Auto-generated by scripts/build-config.js — do not edit directly.
// Source: environment variables. Regenerate with: node scripts/build-config.js
window.APP_CONFIG = {
  supabaseUrl: "https://syqpooenhygbkedfthwe.supabase.co",
  supabaseAnonKey: "sb_publishable_1iHAF45Itws20diDdJG0bg_O1wKk5H2",
  r2PublicUrl: "",
  appName: "IurisIQ Portal",
  firmName: "Katy Chavez, Atty",
};
