// Auto-generated by scripts/build-config.js — do not edit directly.
// Source: environment variables. Regenerate with: node scripts/build-config.js
window.APP_CONFIG = {
  supabaseUrl: "https://syqpooenhygbkedfthwe.supabase.co",
  supabaseAnonKey: "sb_publishable_1iHAF45Itws20diDdJG0bg_O1wKk5H2",
  r2PublicUrl: "",
  appName: "IurisIQ Portal",
  firmName: "Katy Chavez, Atty",
  demoMode: false,
  cfBeaconToken: "",
  turnstileSiteKey: "0x4AAAAAAD5_18ybr8_Swbpp",
  mfaRequiredRoles: [],
  deployVersion: 1785344589330,
};
// Alias used by demo login page and event logger
window.IURISIQ_CONFIG = window.APP_CONFIG;
