// Singleton Supabase client.
// Requires: js/config.js (generated by build-config.js) loaded first.
// Requires: Supabase JS CDN loaded first.

'use strict';

(function () {
  if (typeof window.supabase === 'undefined') {
    throw new Error('[supabase-client] Supabase CDN not loaded. Check script order in HTML.');
  }
  if (!window.APP_CONFIG || !window.APP_CONFIG.supabaseUrl) {
    throw new Error('[supabase-client] APP_CONFIG not set. Run build-config.js first.');
  }

  window.db = window.supabase.createClient(
    window.APP_CONFIG.supabaseUrl,
    window.APP_CONFIG.supabaseAnonKey,
    {
      auth: {
        persistSession: true,
        autoRefreshToken: true,
      },
    }
  );
})();
