// Singleton Supabase client.
// Requires: js/config.js (generated by build-config.js) loaded first.
// Requires: js/vendor/supabase.js loaded first.

'use strict';

(function () {
  if (typeof window.supabase === 'undefined') {
    // js/vendor/supabase.js is same-origin, so this should be rare now -- a
    // blocked/failed script request, not a third-party CDN outage. Without
    // this guard every downstream script (auth.js, login.js) silently never
    // runs, and a login form with no `action` falls through to a raw
    // browser POST / -> 405 the user can't make sense of.
    console.error('[supabase-client] Supabase library failed to load.');

    var warn = function () {
      var banner = document.createElement('div');
      banner.setAttribute('role', 'alert');
      banner.textContent = "This page didn't finish loading. Please refresh — if it keeps happening, try a different network or device.";
      banner.style.cssText = 'position:fixed;top:0;left:0;right:0;z-index:9999;background:#b3261e;color:#fff;padding:12px 16px;text-align:center;font:14px/1.4 system-ui,sans-serif;';
      document.body.prepend(banner);
    };
    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', warn);
    } else {
      warn();
    }

    // Belt-and-suspenders: block every form submit on the page so a form
    // with no `action` can't fall through to a raw browser POST while
    // nothing downstream is wired up to handle it.
    document.addEventListener('submit', function (e) { e.preventDefault(); }, true);
    return;
  }
  if (!window.APP_CONFIG || !window.APP_CONFIG.supabaseUrl) {
    throw new Error('[supabase-client] APP_CONFIG not set. Run build-config.js first.');
  }

  window.db = window.supabase.createClient(
    window.APP_CONFIG.supabaseUrl,
    window.APP_CONFIG.supabaseAnonKey,
    {
      auth: {
        persistSession: true,
        autoRefreshToken: true,
      },
    }
  );
})();
