// WebDAV handler for document drafting.
// Serves .docx files from R2 to Microsoft Word via the WebDAV protocol.
//
// Word opens docs via:  ms-word:ofe|u|https://<host>/webdav/<doc_id>?token=<signed>
//
// Supported methods:
//   PROPFIND  — file metadata (required by Word before GET)
//   GET       — download current version from R2
//   PUT       — receive Word save → AV scan → new version in R2
//   LOCK      — check out (advisory, records who has the file open)
//   UNLOCK    — release check-out
//   OPTIONS   — WebDAV capability advertisement

import { makeAdminClient } from './_helpers.js';
import { scanR2Object } from './_scan.js';

// ── Token auth ─────────────────────────────────────────────────────────────────
// Signed tokens are generated by /api/drafting/open and embedded in the WebDAV URL.
// Format: base64url(JSON{userId,docId,exp}) + '.' + base64url(HMAC-SHA256)

async function verifyWebDAVToken(token, env) {
  if (!token) return null;
  const parts = token.split('.');
  if (parts.length !== 2) return null;

  const [payloadB64, sigB64] = parts;
  const secret = env.WEBDAV_TOKEN_SECRET;
  if (!secret) return null;
  const key = await crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['verify']
  );
  const sig = Uint8Array.from(atob(sigB64.replace(/-/g,'+').replace(/_/g,'/')), c => c.charCodeAt(0));
  const valid = await crypto.subtle.verify('HMAC', key, sig, new TextEncoder().encode(payloadB64));
  if (!valid) return null;

  let payload;
  try { payload = JSON.parse(atob(payloadB64.replace(/-/g,'+').replace(/_/g,'/'))); }
  catch { return null; }
  if (payload.exp < Date.now()) return null;
  return payload; // { userId, docId }
}

export async function generateWebDAVToken(userId, docId, env) {
  const payload = { userId, docId, exp: Date.now() + 8 * 60 * 60 * 1000 }; // 8 hours
  const payloadB64 = btoa(JSON.stringify(payload)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=/g,'');
  const key = await crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(env.WEBDAV_TOKEN_SECRET),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign']
  );
  const sig = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(payloadB64));
  const sigB64 = btoa(String.fromCharCode(...new Uint8Array(sig))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=/g,'');
  return `${payloadB64}.${sigB64}`;
}

// ── Main handler ───────────────────────────────────────────────────────────────

export async function onRequest({ request, env }) {
  const url    = new URL(request.url);
  const method = request.method.toUpperCase();

  // Path structure: /webdav/{token}/{docId}/{filename.docx}
  // Token is in the path (not query string) so Word doesn't strip it on follow-up requests.
  const segments = url.pathname.replace(/^\/webdav\//, '').split('/');
  const token    = segments[0];
  const docId    = segments[1];
  if (!token || !docId) return new Response('Not found', { status: 404 });

  // OPTIONS — capability advertisement (no auth required)
  if (method === 'OPTIONS') {
    return new Response(null, {
      status: 200,
      headers: {
        'DAV': '1,2',
        'Allow': 'OPTIONS,GET,PUT,PROPFIND,LOCK,UNLOCK',
        'MS-Author-Via': 'DAV',
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'OPTIONS,GET,PUT,PROPFIND,LOCK,UNLOCK',
        'Access-Control-Allow-Headers': 'Authorization,Content-Type,Depth,If,Lock-Token,Timeout',
      },
    });
  }

  // Auth — all other methods require a valid signed token
  const payload = await verifyWebDAVToken(token, env);
  if (!payload || payload.docId !== docId) {
    console.error(`[webdav] 401 ${method} — secretSet=${!!env.WEBDAV_TOKEN_SECRET} tokenLen=${token?.length} payloadDocId=${payload?.docId} urlDocId=${docId}`);
    return new Response('Unauthorized', { status: 401,
      headers: { 'WWW-Authenticate': 'Bearer realm="IurisIQ WebDAV"' } });
  }

  const admin = makeAdminClient(env);

  // Load document record
  const { data: doc, error: docErr } = await admin
    .from('draft_documents')
    .select('id, matter_id, file_name, current_version_num, locked_by, lock_token, is_final')
    .eq('id', docId)
    .single();
  if (docErr || !doc) return new Response('Document not found', { status: 404 });

  // Load current version's R2 key
  const { data: ver } = await admin
    .from('draft_document_versions')
    .select('r2_key, size_bytes, created_at')
    .eq('document_id', docId)
    .eq('version_num', doc.current_version_num)
    .single();

  const webdavUrl = `${url.origin}/webdav/${token}/${docId}/${encodeURIComponent(doc.file_name)}`;

  switch (method) {

    // ── PROPFIND ──────────────────────────────────────────────────────────────
    case 'PROPFIND': {
      const size     = ver?.size_bytes ?? 0;
      const modified = ver?.created_at ?? new Date().toISOString();
      const etag     = `v${doc.current_version_num}`;
      const xml = `<?xml version="1.0" encoding="utf-8"?>
<D:multistatus xmlns:D="DAV:">
  <D:response>
    <D:href>${webdavUrl}</D:href>
    <D:propstat>
      <D:prop>
        <D:displayname>${esc(doc.file_name)}</D:displayname>
        <D:getcontentlength>${size}</D:getcontentlength>
        <D:getcontenttype>application/vnd.openxmlformats-officedocument.wordprocessingml.document</D:getcontenttype>
        <D:getlastmodified>${new Date(modified).toUTCString()}</D:getlastmodified>
        <D:getetag>"${etag}"</D:getetag>
        <D:resourcetype/>
        <D:supportedlock>
          <D:lockentry><D:lockscope><D:exclusive/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry>
        </D:supportedlock>
      </D:prop>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
  </D:response>
</D:multistatus>`;
      return new Response(xml, {
        status: 207,
        headers: { 'Content-Type': 'application/xml; charset=utf-8', 'DAV': '1,2', 'MS-Author-Via': 'DAV' },
      });
    }

    // ── GET ───────────────────────────────────────────────────────────────────
    case 'GET': {
      if (!ver?.r2_key) return new Response('No versions found', { status: 404 });
      const obj = await env.R2.get(ver.r2_key);
      if (!obj) return new Response('File not found in storage', { status: 404 });
      return new Response(obj.body, {
        headers: {
          'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
          'ETag': `"v${doc.current_version_num}"`,
          'Last-Modified': ver.created_at ? new Date(ver.created_at).toUTCString() : new Date().toUTCString(),
          'DAV': '1,2',
          'MS-Author-Via': 'DAV',
        },
      });
    }

    // ── PUT ───────────────────────────────────────────────────────────────────
    case 'PUT': {
      if (doc.is_final) {
        return new Response('Document is finalized. Un-finalize before editing.', { status: 423 });
      }
      const body = await request.arrayBuffer();
      if (!body || body.byteLength === 0) {
        return new Response('Empty body', { status: 400 });
      }

      const nextVersion = doc.current_version_num + 1;
      const r2Key = `drafts/${doc.matter_id}/${docId}/v${nextVersion}.docx`;

      await env.R2.put(r2Key, body, {
        httpMetadata: { contentType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' },
      });

      // AV scan every Word save
      const scan = await scanR2Object(env, r2Key);
      if (scan.verdict === 'infected') {
        await env.R2.delete(r2Key).catch(() => {});
        console.warn(`[webdav PUT] INFECTED — deleted ${r2Key}`);
        return new Response('File failed security scan.', { status: 422 });
      }

      await Promise.all([
        admin.from('draft_document_versions').insert({
          document_id: docId,
          version_num: nextVersion,
          r2_key:      r2Key,
          size_bytes:  body.byteLength,
          created_by:  payload.userId,
        }),
        admin.from('draft_documents').update({
          current_version_num: nextVersion,
        }).eq('id', docId),
      ]);

      return new Response(null, {
        status: 204,
        headers: { 'ETag': `"v${nextVersion}"` },
      });
    }

    // ── LOCK ──────────────────────────────────────────────────────────────────
    case 'LOCK': {
      if (doc.locked_by && doc.locked_by !== payload.userId) {
        return new Response('Already locked', { status: 423 });
      }
      const lockToken = `urn:uuid:${crypto.randomUUID()}`;
      await admin.from('draft_documents').update({
        locked_by:  payload.userId,
        locked_at:  new Date().toISOString(),
        lock_token: lockToken,
      }).eq('id', docId);

      const xml = `<?xml version="1.0" encoding="utf-8"?>
<D:prop xmlns:D="DAV:">
  <D:lockdiscovery>
    <D:activelock>
      <D:locktype><D:write/></D:locktype>
      <D:lockscope><D:exclusive/></D:lockscope>
      <D:depth>0</D:depth>
      <D:timeout>Second-28800</D:timeout>
      <D:locktoken><D:href>${lockToken}</D:href></D:locktoken>
      <D:lockroot><D:href>${webdavUrl}</D:href></D:lockroot>
    </D:activelock>
  </D:lockdiscovery>
</D:prop>`;
      return new Response(xml, {
        status: 200,
        headers: {
          'Content-Type': 'application/xml; charset=utf-8',
          'Lock-Token': `<${lockToken}>`,
        },
      });
    }

    // ── UNLOCK ────────────────────────────────────────────────────────────────
    case 'UNLOCK': {
      if (doc.locked_by && doc.locked_by !== payload.userId) {
        return new Response('Cannot unlock: locked by another user.', { status: 403 });
      }
      await admin.from('draft_documents').update({
        locked_by:  null,
        locked_at:  null,
        lock_token: null,
      }).eq('id', docId);
      return new Response(null, { status: 204 });
    }

    default:
      return new Response('Method not allowed', {
        status: 405,
        headers: { 'Allow': 'OPTIONS,GET,PUT,PROPFIND,LOCK,UNLOCK' },
      });
  }
}

function esc(s) {
  return String(s ?? '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}
