// WebDAV handler for editing portal files in desktop Word.
// Serves .docx files from R2 to Microsoft Word via the WebDAV protocol.
// Two kinds of files share this endpoint (selected by the signed token's `kind`):
//   'draft' — doc_drafting module documents (draft_documents + versions)
//   'doc'   — regular matter documents from the Files tab (office_edit module)
//
// Word opens docs via:  ms-word:ofe|u|https://<host>/webdav/<token>/<doc_id>/<name>
//
// Supported methods (Word's save sequence uses ALL of these — a 405 on any of
// them makes Word report "upload failed" even when PUT would succeed):
//   OPTIONS   — WebDAV capability advertisement
//   PROPFIND  — file/collection metadata (Depth-aware)
//   HEAD      — metadata probe (Word checks the file before/after saving)
//   GET       — download current content from R2
//   PUT       — receive Word save → AV scan → persist to R2
//   PROPPATCH — Word sets Win32 timestamps after save; we acknowledge without storing
//   LOCK      — check out (advisory, records who has the file open)
//   UNLOCK    — release check-out

import { makeAdminClient } from './_helpers.js';
import { scanR2Object } from './_scan.js';
import { pruneVersions } from './_versions.js';

const DOCX_MIME = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
const ALLOW = 'OPTIONS,GET,HEAD,PUT,PROPFIND,PROPPATCH,LOCK,UNLOCK';

// ── Token auth ─────────────────────────────────────────────────────────────────
// Signed tokens are generated by /api/drafting/* and /api/office-edit/open and
// embedded in the WebDAV URL *path* (Word strips query strings on follow-up
// requests, so the token must be a path segment).
// Format: base64url(JSON{userId,docId,kind,exp}) + '.' + base64url(HMAC-SHA256)

async function verifyWebDAVToken(token, env) {
  if (!token) return null;
  const parts = token.split('.');
  if (parts.length !== 2) return null;

  const [payloadB64, sigB64] = parts;
  const secret = env.WEBDAV_TOKEN_SECRET;
  if (!secret) return null;
  const key = await crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['verify']
  );
  const sig = Uint8Array.from(atob(sigB64.replace(/-/g,'+').replace(/_/g,'/')), c => c.charCodeAt(0));
  const valid = await crypto.subtle.verify('HMAC', key, sig, new TextEncoder().encode(payloadB64));
  if (!valid) return null;

  let payload;
  try { payload = JSON.parse(atob(payloadB64.replace(/-/g,'+').replace(/_/g,'/'))); }
  catch { return null; }
  if (payload.exp < Date.now()) return null;
  return payload; // { userId, docId, kind }
}

export async function generateWebDAVToken(userId, docId, env, kind = 'draft') {
  const payload = { userId, docId, kind, exp: Date.now() + 8 * 60 * 60 * 1000 }; // 8 hours
  const payloadB64 = btoa(JSON.stringify(payload)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=/g,'');
  const key = await crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(env.WEBDAV_TOKEN_SECRET),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign']
  );
  const sig = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(payloadB64));
  const sigB64 = btoa(String.fromCharCode(...new Uint8Array(sig))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=/g,'');
  return `${payloadB64}.${sigB64}`;
}

export { verifyWebDAVToken };

// ── Main handler ───────────────────────────────────────────────────────────────

export async function onRequest({ request, env }) {
  const url    = new URL(request.url);
  const method = request.method.toUpperCase();

  // Path structure: /webdav/{token}/{docId}/{filename.docx}
  const segments = url.pathname.replace(/^\/webdav\//, '').split('/');
  const token    = segments[0];
  const docId    = segments[1];
  // Word sometimes probes the parent collection: /webdav/{token}/{docId}/
  const isCollection = !segments[2];

  // Every request logged so `wrangler tail` shows exactly where Word's
  // open/save sequence stops. Never log the token itself.
  console.log(`[webdav] ${method} doc=${docId || '-'} coll=${isCollection} depth=${request.headers.get('Depth') ?? '-'} ua="${(request.headers.get('User-Agent') || '').slice(0, 60)}"`);

  if (!token || !docId) return new Response('Not found', { status: 404 });

  // OPTIONS — capability advertisement (no auth required)
  if (method === 'OPTIONS') {
    return new Response(null, {
      status: 200,
      headers: {
        'DAV': '1,2',
        'Allow': ALLOW,
        'Public': ALLOW,
        'MS-Author-Via': 'DAV',
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': ALLOW,
        'Access-Control-Allow-Headers': 'Authorization,Content-Type,Depth,If,Lock-Token,Timeout,Translate,Overwrite',
      },
    });
  }

  // Auth — all other methods require a valid signed token
  const payload = await verifyWebDAVToken(token, env);
  if (!payload || payload.docId !== docId) {
    console.error(`[webdav] 401 ${method} — secretSet=${!!env.WEBDAV_TOKEN_SECRET} tokenLen=${token?.length} payloadDocId=${payload?.docId} urlDocId=${docId}`);
    return new Response('Unauthorized', { status: 401,
      headers: { 'WWW-Authenticate': 'Bearer realm="IurisIQ WebDAV"' } });
  }

  const kind  = payload.kind === 'doc' ? 'doc' : 'draft';
  const admin = makeAdminClient(env);

  // Load a unified file record for either kind.
  //   file = { fileName, size, modified, etag, contentType, lockedBy, lockToken, readOnlyReason }
  let file, draftDoc, regDoc;
  if (kind === 'draft') {
    const { data: doc, error: docErr } = await admin
      .from('draft_documents')
      .select('id, matter_id, file_name, current_version_num, locked_by, lock_token, is_final')
      .eq('id', docId)
      .single();
    if (docErr || !doc) return new Response('Document not found', { status: 404 });
    draftDoc = doc;

    const { data: ver } = await admin
      .from('draft_document_versions')
      .select('r2_key, size_bytes, created_at')
      .eq('document_id', docId)
      .eq('version_num', doc.current_version_num)
      .single();

    file = {
      fileName:       doc.file_name,
      size:           ver?.size_bytes ?? 0,
      modified:       ver?.created_at ?? new Date().toISOString(),
      etag:           `v${doc.current_version_num}`,
      contentType:    DOCX_MIME,
      r2Key:          ver?.r2_key ?? null,
      lockedBy:       doc.locked_by,
      lockToken:      doc.lock_token,
      readOnlyReason: doc.is_final ? 'Document is finalized. Un-finalize before editing.' : null,
    };
  } else {
    const { data: doc, error: docErr } = await admin
      .from('documents')
      .select('id, matter_id, file_name, file_size, r2_key, content_type, status, deleted_at, updated_at, edit_locked_by, edit_lock_token')
      .eq('id', docId)
      .single();
    if (docErr || !doc)                    return new Response('Document not found', { status: 404 });
    if (doc.deleted_at)                    return new Response('Document has been deleted', { status: 404 });
    if (doc.status === 'pending' || doc.r2_key.startsWith('pending/'))
      return new Response('File upload not yet confirmed', { status: 404 });
    regDoc = doc;

    file = {
      fileName:       doc.file_name,
      size:           doc.file_size ?? 0,
      modified:       doc.updated_at ?? new Date().toISOString(),
      etag:           `d${new Date(doc.updated_at ?? Date.now()).getTime()}`,
      contentType:    doc.content_type || DOCX_MIME,
      r2Key:          doc.r2_key,
      lockedBy:       doc.edit_locked_by,
      lockToken:      doc.edit_lock_token,
      readOnlyReason: null,
    };
  }

  const fileHref  = `${url.origin}/webdav/${token}/${docId}/${encodeURIComponent(file.fileName)}`;
  const collHref  = `${url.origin}/webdav/${token}/${docId}/`;

  const fileHeaders = () => ({
    'Content-Type':   file.contentType,
    'Content-Length': String(file.size),
    'ETag':           `"${file.etag}"`,
    'Last-Modified':  new Date(file.modified).toUTCString(),
    'Accept-Ranges':  'none',
    'DAV':            '1,2',
    'MS-Author-Via':  'DAV',
  });

  switch (method) {

    // ── PROPFIND ──────────────────────────────────────────────────────────────
    case 'PROPFIND': {
      const depth = request.headers.get('Depth') ?? '1';
      const fileResponse = `
  <D:response>
    <D:href>${fileHref}</D:href>
    <D:propstat>
      <D:prop>
        <D:displayname>${esc(file.fileName)}</D:displayname>
        <D:getcontentlength>${file.size}</D:getcontentlength>
        <D:getcontenttype>${esc(file.contentType)}</D:getcontenttype>
        <D:getlastmodified>${new Date(file.modified).toUTCString()}</D:getlastmodified>
        <D:getetag>"${file.etag}"</D:getetag>
        <D:resourcetype/>
        <D:supportedlock>
          <D:lockentry><D:lockscope><D:exclusive/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry>
        </D:supportedlock>
      </D:prop>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
  </D:response>`;
      const collResponse = `
  <D:response>
    <D:href>${collHref}</D:href>
    <D:propstat>
      <D:prop>
        <D:displayname>${esc(docId)}</D:displayname>
        <D:resourcetype><D:collection/></D:resourcetype>
        <D:getlastmodified>${new Date(file.modified).toUTCString()}</D:getlastmodified>
      </D:prop>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
  </D:response>`;

      // Collection URL: the collection itself, plus the file when Depth > 0.
      // File URL: just the file.
      const body = isCollection
        ? (depth === '0' ? collResponse : collResponse + fileResponse)
        : fileResponse;

      return new Response(`<?xml version="1.0" encoding="utf-8"?>\n<D:multistatus xmlns:D="DAV:">${body}\n</D:multistatus>`, {
        status: 207,
        headers: { 'Content-Type': 'application/xml; charset=utf-8', 'DAV': '1,2', 'MS-Author-Via': 'DAV' },
      });
    }

    // ── HEAD ──────────────────────────────────────────────────────────────────
    // Word probes with HEAD before and after saving; a 405 here reads as
    // "upload failed" on Word's side.
    case 'HEAD': {
      if (!file.r2Key) return new Response(null, { status: 404 });
      return new Response(null, { status: 200, headers: fileHeaders() });
    }

    // ── GET ───────────────────────────────────────────────────────────────────
    case 'GET': {
      if (!file.r2Key) return new Response('No file content found', { status: 404 });
      const obj = await env.R2.get(file.r2Key);
      if (!obj) return new Response('File not found in storage', { status: 404 });
      return new Response(obj.body, {
        headers: { ...fileHeaders(), 'Content-Length': String(obj.size) },
      });
    }

    // ── PUT ───────────────────────────────────────────────────────────────────
    case 'PUT': {
      if (file.readOnlyReason) {
        return new Response(file.readOnlyReason, { status: 423 });
      }
      const body = await request.arrayBuffer();
      if (!body || body.byteLength === 0) {
        return new Response('Empty body', { status: 400 });
      }

      if (kind === 'draft') {
        const nextVersion = draftDoc.current_version_num + 1;
        const r2Key = `drafts/${draftDoc.matter_id}/${docId}/v${nextVersion}.docx`;

        await env.R2.put(r2Key, body, {
          httpMetadata: { contentType: DOCX_MIME },
        });

        // AV scan every Word save
        const scan = await scanR2Object(env, r2Key);
        if (scan.verdict === 'infected') {
          await env.R2.delete(r2Key).catch(() => {});
          console.warn(`[webdav PUT] INFECTED — deleted ${r2Key}`);
          return new Response('File failed security scan.', { status: 422 });
        }

        await Promise.all([
          admin.from('draft_document_versions').insert({
            document_id: docId,
            version_num: nextVersion,
            r2_key:      r2Key,
            size_bytes:  body.byteLength,
            created_by:  payload.userId,
          }),
          admin.from('draft_documents').update({
            current_version_num: nextVersion,
          }).eq('id', docId),
        ]);

        console.log(`[webdav PUT] draft ${docId} → v${nextVersion} (${body.byteLength} bytes)`);
        return new Response(null, { status: 204, headers: { 'ETag': `"v${nextVersion}"` } });
      }

      // kind === 'doc': regular matter document. Every Word save becomes a new
      // version, same convention as the storage pull (_storage-pull.js
      // importEntry): NEW R2 key → scan → document_versions row → repoint
      // documents.r2_key. The previous version's object stays for history, and
      // an infected save can never clobber the good copy.
      const safeName = String(file.fileName || 'document.docx').replace(/[^\w.\- ]+/g, '_');
      const newKey = `matters/${regDoc.matter_id}/${docId}/${Date.now()}-${safeName}`;
      await env.R2.put(newKey, body, { httpMetadata: { contentType: file.contentType } });

      const scan = await scanR2Object(env, newKey);
      if (scan.verdict === 'infected') {
        await env.R2.delete(newKey).catch(() => {});
        console.warn(`[webdav PUT] INFECTED — rejected save for doc ${docId}`);
        return new Response('File failed security scan.', { status: 422 });
      }

      const { data: maxV } = await admin
        .from('document_versions').select('version_no')
        .eq('document_id', docId)
        .order('version_no', { ascending: false })
        .limit(1).maybeSingle();
      const versionNo = (maxV?.version_no || 1) + 1;

      const v = await admin.from('document_versions').insert({
        document_id: docId,
        version_no:  versionNo,
        r2_key:      newKey,
        file_size:   body.byteLength,
        source:      'portal',
        created_by:  payload.userId,
      });
      if (v.error) {
        await env.R2.delete(newKey).catch(() => {});
        console.error('[webdav PUT] version insert failed:', v.error.message);
        return new Response('Failed to record save.', { status: 500 });
      }

      const now = new Date().toISOString();
      const { data: updated } = await admin
        .from('documents')
        .update({
          r2_key:      newKey,
          file_size:   body.byteLength,
          scan_status: scan.verdict,
          scanned_at:  now,
        })
        .eq('id', docId)
        .select('updated_at')
        .single();

      // Keep history bounded — drop versions older than the newest VERSION_CAP.
      await pruneVersions(env, admin, docId);

      const newEtag = `d${new Date(updated?.updated_at ?? now).getTime()}`;
      console.log(`[webdav PUT] doc ${docId} → v${versionNo} (${body.byteLength} bytes)`);
      return new Response(null, { status: 204, headers: { 'ETag': `"${newEtag}"` } });
    }

    // ── PROPPATCH ─────────────────────────────────────────────────────────────
    // Word sets Win32 file attributes after every save. We don't store them,
    // but we must acknowledge with 207 — a 405 makes Word flag the save as failed.
    case 'PROPPATCH': {
      let props = [];
      try {
        const bodyText = await request.text();
        const propBlock = bodyText.match(/<(?:\w+:)?prop[\s>]([\s\S]*?)<\/(?:\w+:)?prop>/i);
        if (propBlock) {
          props = [...propBlock[1].matchAll(/<(?:\w+:)?([A-Za-z][\w.-]*)[\s/>]/g)]
            .map(m => m[1])
            .filter((v, i, a) => a.indexOf(v) === i);
        }
      } catch { /* acknowledge without echoing props */ }

      const propXml = props.length
        ? props.map(p => `<Z:${p}/>`).join('')
        : '';
      const xml = `<?xml version="1.0" encoding="utf-8"?>
<D:multistatus xmlns:D="DAV:" xmlns:Z="urn:schemas-microsoft-com:">
  <D:response>
    <D:href>${fileHref}</D:href>
    <D:propstat>
      <D:prop>${propXml}</D:prop>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
  </D:response>
</D:multistatus>`;
      return new Response(xml, {
        status: 207,
        headers: { 'Content-Type': 'application/xml; charset=utf-8', 'DAV': '1,2' },
      });
    }

    // ── LOCK ──────────────────────────────────────────────────────────────────
    case 'LOCK': {
      if (file.lockedBy && file.lockedBy !== payload.userId) {
        return new Response('Already locked', { status: 423 });
      }

      // Same user re-locking (or Word refreshing an active lock): reuse the
      // existing token so Word's lock state stays coherent.
      let lockToken = (file.lockedBy === payload.userId && file.lockToken) || null;
      if (!lockToken) {
        lockToken = `urn:uuid:${crypto.randomUUID()}`;
        const lockCols = kind === 'draft'
          ? { locked_by: payload.userId, locked_at: new Date().toISOString(), lock_token: lockToken }
          : { edit_locked_by: payload.userId, edit_locked_at: new Date().toISOString(), edit_lock_token: lockToken };
        await admin.from(kind === 'draft' ? 'draft_documents' : 'documents')
          .update(lockCols).eq('id', docId);
      }

      const xml = `<?xml version="1.0" encoding="utf-8"?>
<D:prop xmlns:D="DAV:">
  <D:lockdiscovery>
    <D:activelock>
      <D:locktype><D:write/></D:locktype>
      <D:lockscope><D:exclusive/></D:lockscope>
      <D:depth>0</D:depth>
      <D:timeout>Second-28800</D:timeout>
      <D:locktoken><D:href>${lockToken}</D:href></D:locktoken>
      <D:lockroot><D:href>${fileHref}</D:href></D:lockroot>
    </D:activelock>
  </D:lockdiscovery>
</D:prop>`;
      return new Response(xml, {
        status: 200,
        headers: {
          'Content-Type': 'application/xml; charset=utf-8',
          'Lock-Token': `<${lockToken}>`,
        },
      });
    }

    // ── UNLOCK ────────────────────────────────────────────────────────────────
    case 'UNLOCK': {
      if (file.lockedBy && file.lockedBy !== payload.userId) {
        return new Response('Cannot unlock: locked by another user.', { status: 403 });
      }
      const clearCols = kind === 'draft'
        ? { locked_by: null, locked_at: null, lock_token: null }
        : { edit_locked_by: null, edit_locked_at: null, edit_lock_token: null };
      await admin.from(kind === 'draft' ? 'draft_documents' : 'documents')
        .update(clearCols).eq('id', docId);
      return new Response(null, { status: 204 });
    }

    default:
      return new Response('Method not allowed', {
        status: 405,
        headers: { 'Allow': ALLOW },
      });
  }
}

function esc(s) {
  return String(s ?? '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}
