#!/usr/bin/env node
// Generates js/config.js from env vars at build time (or local .env for dev).
// Supabase anon key is public by design — RLS enforces security, not key secrecy.
'use strict';

const fs = require('fs');
const path = require('path');

// Capture whether SUPABASE_URL was preset in the shell BEFORE loading .env. A
// shell-preset value silently overrides .env (below) and has cross-wired the
// wrong client's Supabase project into a build before — the guard further down
// surfaces that loudly.
const supabaseFromShell = !!process.env.SUPABASE_URL;

// Load .env as FILL-IN for anything the shell didn't set. This must run even
// when SUPABASE_URL is preset (the node -e deploy command): skipping .env in
// that case silently dropped TURNSTILE_SITE_KEY from the build — the login
// captcha vanished on every inline-env deploy. Shell-set vars always win
// (the `if (!process.env[key])` below never overrides them).
try {
  const envPath = path.join(__dirname, '..', '.env');
  const lines = fs.readFileSync(envPath, 'utf8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx === -1) continue;
    const key = trimmed.slice(0, idx).trim();
    const val = trimmed.slice(idx + 1).trim().replace(/^["']|["']$/g, '');
    if (val && !process.env[key]) process.env[key] = val;
  }
} catch (_) {
  console.warn('[build-config] No .env file found — using environment variables only');
}

const required = ['SUPABASE_URL', 'SUPABASE_ANON_KEY'];
const missing = required.filter(k => !process.env[k]);
if (missing.length) {
  console.error('[build-config] Missing required env vars:', missing.join(', '));
  process.exit(1);
}

// Wrong-project guard: make the target Supabase project impossible to miss, and
// shout if SUPABASE_URL came from the shell (the usual way the wrong client's
// config gets built by accident).
const projectRef = (String(process.env.SUPABASE_URL).match(/\/\/([a-z0-9]+)\.supabase\.co/) || [])[1] || '(unknown)';
if (supabaseFromShell) {
  console.warn(`[build-config] WARNING: SUPABASE_URL came from the SHELL environment, not .env — building for project '${projectRef}'. Confirm this is the intended client before deploying!`);
} else {
  console.log(`[build-config] SUPABASE_URL from .env — building for project '${projectRef}'.`);
}

// Captcha guard: an empty site key means the login CAPTCHA silently disappears
// from the deployed portal — always worth a shout.
if (!process.env.TURNSTILE_SITE_KEY) {
  console.warn('[build-config] WARNING: TURNSTILE_SITE_KEY is empty — the login CAPTCHA will NOT render in this build!');
}

const isDemoMode = process.env.DEMO_MODE === 'true';

// MFA_REQUIRED_ROLES: comma-separated role names, or 'none' to disable MFA
// firm-wide (per-firm request, e.g. SSL). Unset → null → js/auth.js applies the
// template default (Owner/Attorney/Partner Attorney). NOTE: use 'none', not an
// empty value — the .env loader above skips empty values.
const mfaRolesRaw = process.env.MFA_REQUIRED_ROLES;
const mfaRequiredRoles =
  mfaRolesRaw === undefined ? null
  : mfaRolesRaw.trim().toLowerCase() === 'none' ? []
  : mfaRolesRaw.split(',').map(s => s.trim()).filter(Boolean);
if (mfaRequiredRoles && mfaRequiredRoles.length === 0) {
  console.warn('[build-config] NOTE: MFA is DISABLED firm-wide in this build (MFA_REQUIRED_ROLES=none).');
}

const config = `// Auto-generated by scripts/build-config.js — do not edit directly.
// Source: environment variables. Regenerate with: node scripts/build-config.js
window.APP_CONFIG = {
  supabaseUrl: ${JSON.stringify(process.env.SUPABASE_URL)},
  supabaseAnonKey: ${JSON.stringify(process.env.SUPABASE_ANON_KEY)},
  r2PublicUrl: ${JSON.stringify(process.env.R2_PUBLIC_URL || '')},
  appName: "IurisIQ Portal",
  firmName: ${JSON.stringify(process.env.FIRM_NAME || 'Your Firm Name')},
  demoMode: ${isDemoMode},
  cfBeaconToken: ${JSON.stringify(process.env.CF_BEACON_TOKEN || '')},
  turnstileSiteKey: ${JSON.stringify(process.env.TURNSTILE_SITE_KEY || '')},
  mfaRequiredRoles: ${JSON.stringify(mfaRequiredRoles)},
  deployVersion: ${Date.now()},
};
// Alias used by demo login page and event logger
window.IURISIQ_CONFIG = window.APP_CONFIG;
`;

const outPath = path.join(__dirname, '..', 'js', 'config.js');
fs.writeFileSync(outPath, config, 'utf8');
console.log('[build-config] Wrote js/config.js');
