#!/usr/bin/env node
// Generates js/config.js from env vars at build time (or local .env for dev).
// Supabase anon key is public by design — RLS enforces security, not key secrecy.
'use strict';

const fs = require('fs');
const path = require('path');

// Load .env for local dev (skip if already set by Netlify)
if (!process.env.SUPABASE_URL) {
  try {
    const envPath = path.join(__dirname, '..', '.env');
    const lines = fs.readFileSync(envPath, 'utf8').split('\n');
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const idx = trimmed.indexOf('=');
      if (idx === -1) continue;
      const key = trimmed.slice(0, idx).trim();
      const val = trimmed.slice(idx + 1).trim().replace(/^["']|["']$/g, '');
      if (!process.env[key]) process.env[key] = val;
    }
  } catch (_) {
    console.warn('[build-config] No .env file found — using environment variables only');
  }
}

const required = ['SUPABASE_URL', 'SUPABASE_ANON_KEY'];
const missing = required.filter(k => !process.env[k]);
if (missing.length) {
  console.error('[build-config] Missing required env vars:', missing.join(', '));
  process.exit(1);
}

const config = `// Auto-generated by scripts/build-config.js — do not edit directly.
// Source: environment variables. Regenerate with: node scripts/build-config.js
window.APP_CONFIG = {
  supabaseUrl: ${JSON.stringify(process.env.SUPABASE_URL)},
  supabaseAnonKey: ${JSON.stringify(process.env.SUPABASE_ANON_KEY)},
  r2PublicUrl: ${JSON.stringify(process.env.R2_PUBLIC_URL || '')},
  appName: "IurisIQ Portal",
  firmName: ${JSON.stringify(process.env.FIRM_NAME || 'Your Firm Name')},
};
`;

const outPath = path.join(__dirname, '..', 'js', 'config.js');
fs.writeFileSync(outPath, config, 'utf8');
console.log('[build-config] Wrote js/config.js');
