// DRAFT COPY: Max rewrites these (D-87, after launch).
//
// COPY and APPROVED are the v2 Lab's copy.js (ui-lab-v2/copy.js), carried over
// as they are. PORTAL, at the bottom, holds the few strings the real page needs
// that the Lab never had (real uploads, size limits, server errors, finding a
// case), plus replacements for Lab sentences that describe the sketch rather
// than the product ("Lost on reload", "Nothing is sent"). PORTAL wins over
// COPY for the same key. All of PORTAL is placeholder copy too.
//
// Every new user-facing string in the v2 Lab lives in COPY below, as
// placeholders. Max writes product copy. {name} marks a value filled in at
// runtime. No em dashes.
//
// APPROVED, at the bottom, is not draft: those strings are reused verbatim from
// the 1.2 Lab, the portal contract, or the master record, and are kept here only
// so the page has one place for text.

export const COPY = {
  // ── Shell ──
  'nav.rulebook': 'Rulebook',
  'nav.old_checker': 'Proof Scan (current)',
  'case.folder_new': 'New case',
  'people.main': 'Main person: {role}',
  'people.unnamed': 'Name not yet known',
  'people.from_scan': 'From the scanned package',
  'people.heading': 'Other people on this case',
  'ref.heading_main': 'Main person',
  'people.hint': 'Usually two people, sometimes three. Documents are matched to the person they belong to.',
  'people.add': 'Add person',
  'people.remove': 'Remove',
  'people.role': 'Role',
  'people.belongs': 'Belongs to',
  'people.main_short': 'Main person',
  'role.applicant': 'Applicant',
  'role.beneficiary': 'Beneficiary',
  'role.petitioner': 'Petitioner',
  'role.sponsor': 'Sponsor',
  'role.joint_sponsor': 'Joint sponsor',
  'role.household_member': 'Household member',
  'summary.empty_general': 'No details yet. Add evidence in Evidence Zero, or go straight to a stage. A Physical Scan fills these from the package.',
  'ez.drop.kept': 'Read, not kept. Only the facts stay with the case.',
  'ez.fact.spouse_1': 'Spouse',
  'ez.fact.spouse_2': 'Spouse',
  'ez.fact.marriage_date': 'Married',
  'ez.type.birth_certificate': 'Birth certificate',
  'ez.type.marriage_certificate': 'Marriage certificate',
  'ps.fixture.general': 'General: AOS-style package',
  'ps.people.heading': 'People and evidence in this package',
  'ps.people.forms': 'Forms',
  'ps.people.evidence': 'Evidence',
  'ps.people.none': 'No evidence for this person in the package.',
  'ps.people.pages': '{n} pages',
  'ps.people.new_card': 'New case card from this scan',
  'limit.note': 'PDF, up to 12 MB. If a file is larger, reduce it and add it again.',
  'shell.footer': 'Local v2 Lab',
  'shell.topbar_note': 'Local preview, v2 sketch',
  'shell.preview_note': 'Preview only. Nothing is scanned, stored, or sent. Every document here is a synthetic sample.',
  'masthead.kicker': 'Intake & Screening · Proof Scan v2',
  'masthead.title': 'Every case, checked at the right stage.',
  'masthead.sub': 'Start with the case type. Evidence Zero comes first, then each stage checks what should exist by then.',

  // ── Entry (D-56) ──
  'entry.heading': 'Start',
  'entry.case_type_label': 'Case type',
  'entry.case_type_placeholder': 'Select a case type…',
  'entry.case_type_hint': 'It decides which rules exist, and it is locked once the case starts.',
  'entry.start': 'Start',
  'choose.heading': 'Choose a stage',
  'choose.sub': 'Evidence Zero is ready. Pick what you are checking now.',
  'shell.reset': 'Reset preview',
  'entry.stage_label': 'Stage',
  'entry.stage_hint': 'Enter at any stage. A confirmed reference record helps, but it is never required.',
  'entry.stages_locked': 'The other stages open once Evidence Zero has {missing}.',
  'gate.ead_doc': 'an EAD',
  'gate.ead_facts': 'the EAD details (name, date of birth, A-Number, expiration)',
  'gate.address': 'the address',
  'gate.approve': 'an approved record',
  'ref.gate': 'Before drafting, add {missing}.',
  'ref.noead.ask': 'There is no evidence for this case',
  'ref.noead.warn': 'Only if there really is no evidence. The record will have no document behind it.',
  'ref.noead.confirm': 'Move forward without evidence',
  'ref.noead.on': 'No evidence for this case',
  'ref.noead.undo': 'Undo',
  'track.todo': 'Not started',
  'track.current': 'You are here',
  'track.done': 'Done',
  'track.attention': 'Needs attention',
  'track.locked': 'Locked',
  'track.optional': 'Optional',
  'summary.heading': 'Case summary',
  'summary.empty': 'No client details yet. Add the EAD below, or fill in the reference record.',
  'summary.name': 'Client',
  'summary.case': 'Case',
  'summary.approved': 'Record approved',
  'summary.not_approved': 'Record not approved',
  'summary.changed': 'Changed since approval',
  'summary.edit': 'Edit in Evidence Zero',
  'stage.evidence_zero.desc': 'Documents and facts, kept for the whole case.',
  'stage.draft_review.desc': 'Check draft forms against the reference record and the checklist.',
  'stage.preflight.desc': 'Check the client\'s corrections, signatures and card details.',
  'stage.physical_scan.desc': 'The full final check of the prepared package.',

  // ── Placeholders for undecided questions ──
  'open.label': 'Open: {q}',
  'open.not_asked': 'not yet asked',

  // ── Evidence Zero (D-53 to D-55) ──
  'ez.docs.heading': 'Documents',
  'ez.intro': 'Proof Scan identifies each document and keeps the facts that matter for this case. Nothing here is counted or flagged.',
  'ez.add.label': 'Add document',
  'ez.add.note': 'Samples only. No file is read.',
  'ez.docs.empty': 'No documents yet. The reference record below works without any.',
  'ez.doc.identified': 'Identified as {type}',
  'ez.doc.status_review': 'Source needs review',
  'ez.doc.unreadable_value': 'Could not be read',
  'ez.doc.not_on_document': 'Not on this document',
  'ez.doc.source_review': 'This copy could not be read reliably. Please review the source document. Nothing from it was used or compared, so it cannot create a discrepancy.',
  'ez.doc.correct_type': 'Type',
  'ez.doc.type_corrected': 'Type corrected by staff',
  'ez.type.ead': 'EAD card',
  'ez.type.intake': 'Intake',
  'ez.type.other': 'Other document',
  'ez.doc.remove': 'Remove from workspace',
  'ez.note.replaced': 'The newer {type} replaced the earlier one in this workspace. Any difference is proposed below, never applied on its own.',
  'ez.note.older_not_kept': 'A newer {type} is already here, so this older one was not kept.',
  'ez.fact.name': 'Name',
  'ez.fact.date_of_birth': 'Date of birth',
  'ez.fact.a_number': 'A-Number',
  'ez.fact.ead_expiration': 'Expires',
  'ez.fact.address': 'Address',
  'ez.fact.phone': 'Phone',
  'ez.fact.email': 'Email',
  'ez.fact.ssn': 'SSN',
  'ez.expected.heading': 'Expected in the final package',
  'ez.expected.hint': 'Set by the {case_type} checklist, not marked by staff.',
  'ez.expected.on_file': 'On file here',
  'ez.expected.not_on_file': 'Not on file here yet',

  // ── Reference record (D-10 to D-13, D-45, D-55) ──
  'ref.heading': 'Reference record',
  'ref.hint': 'Every field stays editable. Approve once it looks right.',
  'ref.status.not_approved': 'Not approved yet',
  'ref.status.changed': 'Changed since approval. Approve again when ready.',
  'ref.status.approved': 'Approved at {time}',
  'ref.group.name': 'Name',
  'ref.group.address': 'Address',
  'ref.group.identity': 'Identity',
  'ref.group.contact': 'Contact',
  'ref.group.ssn': 'SSN',
  'ref.source.none': 'Not yet provided',
  'ref.source.doc': 'From {label}',
  'ref.source.staff': 'Entered by staff',
  'ref.proposal': '{label} shows {value}. The record has {current}.',
  'ref.proposal.from': 'Suggested by {label}',
  'ref.proposal.use': 'Use this value',
  'ref.proposal.keep': 'Keep current value',
  'ref.ssn.not_provided': 'Not yet provided',
  'ref.ssn.pending_state': 'Not yet provided. That is a normal state, not a problem.',
  'ref.ssn.nine_digits': 'Nine digits.',
  'ssn.show': 'Show SSN',
  'ssn.hide': 'Hide SSN',
  'ref.date_format': 'Use MM/DD/YYYY.',
  'ref.approve': 'Approve reference record',
  'ref.approved_btn': 'Approved',
  'ref.missing_ok': '{n} fields are empty. That does not block approval.',
  'ref.all_filled': 'Every field has a value.',

  'field.first_name': 'First name',
  'field.middle_name': 'Middle name',
  'field.last_name': 'Last name',
  'field.street': 'Street number and name',
  'field.apt_type': 'Apt. / Ste. / Flr.',
  'field.apt_number': 'Number',
  'field.city': 'City or town',
  'field.state': 'State',
  'field.zip': 'ZIP code',
  'field.in_care_of': 'In care of',
  'field.province': 'Province',
  'field.postal_code': 'Postal code',
  'field.country': 'Country',
  'field.date_of_birth': 'Date of birth',
  'field.a_number': 'A-Number',
  'field.ead_expiration': 'EAD expiration',
  'field.phone': 'Phone',
  'field.email': 'Email',
  'field.ssn': 'SSN',

  // The same fields, mid-sentence.
  'field_in.name': 'name',
  'field_in.address': 'address',
  'field_in.first_name': 'first name',
  'field_in.middle_name': 'middle name',
  'field_in.last_name': 'last name',
  'field_in.street': 'street',
  'field_in.apt_type': 'Apt./Ste./Flr.',
  'field_in.apt_number': 'apartment, suite or floor number',
  'field_in.city': 'city',
  'field_in.country': 'country',
  'field_in.state': 'state',
  'field_in.zip': 'ZIP code',
  'field_in.in_care_of': 'in care of name',
  'field_in.province': 'province',
  'field_in.postal_code': 'postal code',
  'field_in.date_of_birth': 'date of birth',
  'field_in.a_number': 'A-Number',
  'field_in.ead_expiration': 'EAD expiration',
  'field_in.phone': 'phone',
  'field_in.email': 'email',
  'field_in.ssn': 'SSN',

  // ── Draft Review and Pre-flight (D-56, D-57, D-47, D-16) ──
  'review.preflight.optional': 'Use it after the client signs and sends corrections, before printing.',
  'review.draft_review.heading': 'Draft Review',
  'review.preflight.heading': 'Pre-flight',
  'review.results': 'Review Results',
  'scope.label': 'Review scope',
  'scope.individual': 'Individual review',
  'scope.whole': 'Whole review',
  'scope.individual.draft_review': 'One form, against the reference record and its own checks. The rest of the package is ignored.',
  'scope.whole.draft_review': 'The complete draft form set.',
  'scope.individual.preflight': 'One form or document, on its own.',
  'scope.whole.preflight': 'Every corrected form you upload, checked together. Forms you leave out are not expected.',
  'review.drop.title.draft_review': 'Add the drafts',
  'review.drop.title.preflight': 'Add the corrected forms',
  'review.drop.meta.whole': 'One combined PDF or separate files.',
  'review.drop.meta.individual': 'The one form picked above.',
  'review.drop.ready': 'Ready for review',
  'review.files': 'Files',
  'files.one': '1 file',
  'files.many': '{n} files',
  'files.page': '1 page',
  'files.pages': '{n} pages',
  'files.use_instead': 'Use {label} instead',
  'pf.corr.file.marked': 'Client markups',
  'pf.corr.file.corrected': 'Corrected pages',
  'review.show_grouping': 'How the forms were grouped',
  'pf.corr.drop.title': 'Client markups and corrected pages',
  'pf.corr.drop.ready': 'Markups and corrections added',
  'ez.drop.title': 'Add a document',
  'ez.drop.meta': 'EAD, intake, or other evidence.',
  'ez.drop.added': '{type} added',
  'scan.running': 'Reviewing…',
  'scan.done': 'Review complete',
  'ps.drop.title': 'Add the scanned package',
  'ps.drop.meta': 'The printed package, scanned.',
  'ps.drop.ready': 'Package ready',
  'ps.casecard_diff_person': 'The scanned package shows the {role}\'s {field} as {scanned}. The {role}\'s case card has {card}.',
  'ps.people.shared': 'Shared',
  'match.heading': 'Evidence matches the forms',
  'match.note': 'Every fact on a document is checked against the forms about the same person.',
  'match.and': 'and',
  'match.doc': 'The {owner}\'s {evidence}',
  'match.ok': 'matches the {forms} ({fields}).',
  'match.bad_short': 'Shows {field} {ev}; the {form} has {fv}.',
  'match.diff': 'The {owner}\'s {evidence} shows {field} {ev}. The {form} has {fv}.',
  'field_in.marriage_date': 'marriage date',
  'people.from_forms': 'From the draft forms (not evidence)',
  'people.main_tag': 'Main',
  'ps.casecard_diff': 'The scanned package shows {field} {scanned}. The case card has {card}.',
  'ps.file.meta': 'Scanned package',
  'ps.run': 'Run Physical Scan',
  'signoff.title': 'Mark this stage reviewed',
  'signoff.on': 'Stage reviewed',
  'signoff.sub': 'Check once the issues are corrected. The tracker moves on; the report stays as it is.',
  'signoff.next': 'Go to {stage}',
  'track.signed': 'Reviewed',
  'review.add_whole.draft_review': 'Add drafts',
  'review.add_whole.preflight': 'Add prepared package',
  'review.pick_form': 'Form',
  'review.add_individual': 'Add sample draft',
  'review.grouped': 'Forms identified automatically: {n}',
  'review.individual_ready': 'Sample {form} ready.',
  'review.found_in': '{file}, p.{pages}',
  'review.run.draft_review': 'Run Draft Review',
  'review.run.preflight': 'Run Pre-flight',
  'review.run_note': 'Nothing is sent. The result is simulated from sample data.',
  'review.add_first': 'Add a sample first.',
  'review.individual_file': '{form}, individual review',
  'review.n_files': '{n} files',

  'review.our_errors': 'Our errors',
  'review.our_errors.note': 'Inconsistencies across the forms, and values that differ from the reference record. A difference shows both values and where each came from.',
  'review.our_errors.none': 'Nothing to compare yet.',
  'review.mismatch': '{form} has {field} {draft}. The reference record has {ref}.',
  'review.mismatch_person': '{form} has the {role}\'s {field} {draft}. The {role}\'s case card has {ref}.',
  'review.mismatch_person_blank': '{form} has no {field} for the {role}. The {role}\'s case card has {ref}.',
  'review.mismatch_blank': '{form} has no {field}. The reference record has {ref}.',
  'review.draft_value': 'Draft',
  'review.reference_value': 'Reference record',
  'review.blank': 'blank',
  'review.resolve_label': 'To resolve',
  'review.resolve_text': 'Correct the draft, or correct the reference record if the draft is right.',
  'review.edit_reference': 'Edit the reference record',
  'review.consistency_group': 'Consistency across forms',

  'review.checklist': 'Checklist items',
  'review.missing_form': '{form} is not in the draft set. A whole Draft Review expects every {case_type} form.',
  'review.expected_by': 'Why',
  'review.expected_by_text': 'A whole Draft Review expects the complete {case_type} form set.',
  'review.included': 'Included in the review',

  'review.needs_info': 'Needs info',
  'review.needs_info.note': 'Information not obtained yet. Listed for follow-up. Not counted, and not an error at this stage.',
  'review.needs_info_row': '{field} is not obtained yet. Blank on {forms}.',

  'review.needs_info_check': '{form}: {title}. Blank for now, checked once filled in.',
  'review.confirm': 'Please confirm',
  'review.confirm.note': 'Not an error. Not counted. Just making sure it was intended.',
  'review.confirm_row': '{title}. Was this intended?',
  'review.cleared_soft': '{a} cleared, {b} to follow up',
  'review.notifications': 'For awareness',
  'review.notifications.note': 'Not counted.',
  'review.pf_missing_evidence': 'The {item} copy is not in the prepared package yet. The final package expects it: {label}.',
  'review.pf_no_reference': '{field} was never added to the reference record. It appears on {forms}.',
  'ps.no_reference': 'Never added to the reference record: {fields}.',
  'ps.no_reference.note': 'Not counted. The forms are still checked against each other.',

  // ── Pre-flight corrections check (Max 2026-10-02) ──
  'pf.corr.add_label': 'Client corrections',
  'pf.corr.optional': 'Optional. The pages the client marked up, and the pages you corrected.',
  'pf.corr.added': 'Marked up: {marked}. Corrected: {corrected}.',
  'pf.corr.heading': 'Client corrections',
  'pf.corr.note': 'Handwriting is read by OCR and can be wrong. Treat these as pointers, not verdicts.',
  'pf.corr.fixed': '{form} p.{page}: {field} corrected. Now {corrected}.',
  'pf.corr.not_fixed': '{form} p.{page} still has {field} {original}. The client marked {markup}.',
  'pf.corr.differs': '{form} p.{page} has {field} {corrected}. The markup seems to say {markup}.',
  'pf.corr.unclear': '{form} p.{page}: the handwritten {field} could not be read clearly. Check it against {corrected} by hand.',
  'pf.corr.not_carried': '{other} {other_where} still has {field} {other_value}. It was corrected to {corrected} on the {form}.',
  'pf.corr.omitted_ok': '{form} p.{page}: the client wrote {markup} as the country. Left off US addresses on purpose.',
  'pf.corr.consistency': 'The {field} does not match across forms. A client correction was not carried to every form. See Client corrections.',
  'pf.corr.no_page': '{form} p.{page}: the client marked {field} as {markup}. No corrected {form} page was added.',
  'pf.corr.tag.no_page': 'No corrected page',
  'pf.corr.tag.fixed': 'Fixed',
  'pf.corr.tag.not_carried': 'Not carried over',
  'pf.corr.tag.omitted_ok': 'Left out on purpose',
  'pf.corr.tag.not_fixed': 'Not fixed',
  'pf.corr.tag.differs': 'Check',
  'pf.corr.tag.unclear': 'Unreadable',
  'pf.corr.source': 'Pre-flight correction ({form} p.{page})',
  'pf.corr.sent': '{n} corrected value(s) sent to Evidence Zero for review. ',
  'pf.corr.review_ez': 'Review in Evidence Zero',

  'review.pending': 'Checked at a later stage',
  'review.not_applicable': 'Not checked at this stage',
  'review.unmapped_label': 'Not in the sample mapping',
  'review.unmapped': 'No stage state for these checks yet.',

  // ── Physical Scan (D-58) ──
  'ps.intro': 'The full final check: every form, the expected evidence, and the firm checklist.',
  'ps.missing_item': '{item} is not in the package. The {case_type} package definition includes it.',

  // ── Possible issues (D-59) ──
  'pi.powerless': 'Suggestions only. Never counted, never emailed.',
  'pi.never': 'Suppressed for the whole firm, every case type. Listed in the Rulebook.',
  'pi.dismissed': 'Dismissed: {choice}.',

  // ── Suggest as a future rule (D-60) ──
  'suggest.wording': 'Rule wording',
  'suggest.scope': 'Scope',
  'suggest.scope.case': 'This case type (DACA renewal)',
  'suggest.scope.firm': 'Firm-wide (every case type)',
  'suggest.scope.recommended': 'Suggested scope: this case type. A sample recommendation; change it if needed.',
  'suggest.future_only': 'A new rule affects future scans only. Results already run keep the rules they ran with.',
  'suggest.save': 'Add to the rulebook',
  'suggest.cancel': 'Cancel',
  'suggest.added_btn': 'Added to the rulebook',
  'suggest.added': 'Added to the rulebook. Affects future scans only; this result is unchanged.',

  // ── Email (D-61, D-43) ──
  'email.toggle': 'Email the result',
  'email.hint': 'Off unless turned on. Sends only the stage result and a link to the report.',
  'email.not_sent': 'Preview only. Nothing is sent.',
  'email.to': 'To',
  'email.to_value': 'Firm notification address (not set in this preview)',
  'email.subject': 'Subject',
  'email.subject_value': 'Proof Scan, {case_type}, {stage}: {phrase}',
  'email.body_result': '{stage} result: {phrase}',
  'email.body_link': 'Open the report:',
  'email.link_value': 'https://portal.example.test/proof-scan/report/sample',

  // ── Rulebook (D-60, D-61) ──
  'rulebook.kicker': 'Proof Scan · Rulebook',
  'rulebook.title': 'The rules, in one place.',
  'rulebook.sub': 'Firm-wide rules apply to every case type. Case-type rules add to them. Added rules last until reload in this preview.',
  'rulebook.add': 'Add a rule',
  'rulebook.edit': 'Edit',
  'rulebook.edit.save': 'Save rule',
  'rulebook.edited': 'Edited',
  'rulebook.add.title': 'Rule',
  'rulebook.add.title_ph': 'What must be true, e.g. the observed fact, then the expectation.',
  'rulebook.add.form': 'Form',
  'rulebook.add.form_any': 'Any form',
  'rulebook.add.page': 'Page',
  'rulebook.add.item': 'Item',
  'rulebook.add.scope': 'Scope',
  'rulebook.add.save': 'Add to rulebook',
  'rulebook.add.cancel': 'Cancel',
  'rulebook.add.need_title': 'Write the rule first.',
  'rulebook.origin.staff': 'Added by staff',
  'rulebook.added_where': 'Added this session. Lost on reload.',
  'rulebook.firm': 'Firm-wide rules',
  'rulebook.firm.note': 'General rules. They run on every case type and every package.',
  'rulebook.case': '{case_type} rules',
  'rulebook.case.note': 'From the firm\'s own checklist. Added to the firm-wide rules, never replacing them.',
  'rulebook.whole_package': 'Whole package',
  'rulebook.added_group': 'Added by staff',
  'rulebook.kept': 'Kept on the checklist, not scanned',
  'rulebook.kept.note': 'Physical and process steps. They stay on the checklist and are not checked from a PDF.',
  'rulebook.check.process': 'Process step',
  'rulebook.check.physical': 'Physical item',
  'rulebook.suppressed': 'Suppressed reasoning',
  'rulebook.suppressed.note': 'Possible issues never suggest these again, for any case type.',
  'rulebook.suppressed_seed': 'Signature date order',
  'rulebook.scope.firm': 'Firm-wide',
  'rulebook.scope.case': '{case_type}',
  'rulebook.scope.all': 'Firm-wide, all case types',
  'rulebook.origin.base': 'General rules',
  'rulebook.origin.checklist': 'Firm checklist',
  'rulebook.origin.learned': 'Suggested from a possible issue',
  'rulebook.origin.r1': 'Retired 2026-08-21',
  'rulebook.origin.dismissal': 'Dismissed from a possible issue',
  'rulebook.future_only': 'Affects future scans only',
  'rulebook.learned_where': 'Added this session from {stage}. Lost on reload.',
};

export const APPROVED = {
  // D-52: the four stage names are product language.
  'stage.evidence_zero': 'Evidence Zero',
  'stage.draft_review': 'Draft Review',
  'stage.preflight': 'Pre-flight',
  'stage.physical_scan': 'Physical Scan',

  // D-23, exactly, and the D-24 reminder as the portal contract spells it
  // (proof-scan-contract.js STAFF_REVIEW_REMINDER).
  'state.attention_one': '1 item needs attention',
  'state.attention_many': '{n} items need attention',
  'state.incomplete': 'Review incomplete',
  'state.clear': 'No issues found',
  'state.reminder': 'Staff review is still required before filing.',

  // 1.2 report.js row and fold wording.
  'r12.all_cleared': 'all {n} cleared',
  'r12.some_cleared': '{a}/{b} cleared',
  'r12.expects': 'Checklist expects',
  'r12.where': 'Where',
  'r12.note': 'Note',
  'r12.why_not_checked': 'Why it could not be checked',
  'r12.not_checked': 'Not checked',
  'r12.package_group': 'Complete runthrough',

  // 1.2 Lab chrome around the report.
  'r12.fixture_label': 'Report fixture',
  'r12.fixture.1': 'Known-good DACA',
  'r12.fixture.2': "Today's false positives",
  'r12.fixture.3': 'Error-injected',
  'r12.fixture.4': 'Everything wrong',
  'r12.clear': 'Clear',
  'r12.scan_results': 'Scan Results',
};

// Placeholder copy the real page needs on top of the Lab's. Same rules: Max
// rewrites it, {name} is filled at runtime, no em dashes.
export const PORTAL = {
  // ── Shell ──
  'masthead.kicker': 'Intake & Screening · Proof Scan v2',
  'nav.scan': 'Cases',
  'shell.loading': 'Loading…',
  'shell.error': 'Something went wrong: {error}',
  'shell.retry': 'Try again',

  // ── Start and finding a case (D-77, D-83) ──
  'entry.folder_hint': 'The case names itself from the people on it once a document or scan shows their names. Find it later by a name or an A-Number.',
  'find.heading': 'Find a case',
  'find.label': 'Client name or A-Number',
  'find.placeholder': 'e.g. Rivera or A-123456789',
  'find.search': 'Search',
  'find.recent': 'Recent cases',
  'find.none': 'No cases match.',
  'find.empty': 'No cases yet.',
  'case.back': 'All cases',

  // ── Uploads and size limits (D-95) ──
  'limit.note': 'PDF, JPEG, PNG or WebP. Up to 12 MB per file and 22 MB per review. If it is larger, reduce it and add it again.',
  'limit.note_one': 'PDF, JPEG, PNG or WebP, up to 12 MB. If it is larger, reduce it and add it again.',
  'limit.file_too_big': '{name} is {mb} MB. The limit is 12 MB per file. Reduce it and add it again.',
  'limit.total_too_big': 'These files add up to {mb} MB. The limit is 22 MB per review. Reduce them and try again.',
  'limit.too_many': 'Add at most {n} files at a time.',
  'limit.wrong_type': '{name}: only PDF, JPEG, PNG or WebP files can be read.',
  'limit.empty': '{name} is empty.',
  'files.choose': 'Choose files',
  'files.choose_one': 'Choose a file',
  'files.add_more': 'Add more',
  'files.remove': 'Remove',
  'files.clear': 'Clear',
  'files.size': '{mb} MB',
  'files.total': '{n} files, {mb} MB of 22 MB',
  'ez.drop.meta': 'EAD, intake, or other evidence. One document at a time is read.',
  'ez.reading': 'Reading {name}…',
  'ez.drop.title': 'Add a document',
  'ez.doc.not_kept': 'Read, not kept. Only the facts stay with the case.',

  // ── Reference record, server-backed ──
  'ref.saving': 'Saving…',
  'ref.saved_error': 'Not saved: {error}',
  'ref.gate.heading': 'Evidence requirement',
  'ref.gate.ready': 'The evidence requirement is met. The stages are open.',
  'ref.heading_person': '{role}',
  'people.make_main': 'Make main person',
  'people.cannot_remove_main': 'Choose another main person before removing this card.',
  'ref.ssn.reveal_first': 'Press the eye to see or change the SSN.',

  // ── Stages, server-backed ──
  'review.files_heading': 'Files',
  'review.run_note': 'The files are read for this review and not kept. The result is saved to the case.',
  'review.add_files_first': 'Add the files first.',
  'review.pick_form_hint': 'The form this individual review is about.',
  'review.not_this_stage_count': 'Not checked at this stage: {n}.',
  'review.observed': 'Observed',
  'match.in_package': '(in the package)',
  'review.stored_run': 'Last run {when}',
  'review.no_run': 'Not run yet.',
  'review.not_stored': 'This review completed but could not be saved to the case. It will not be here next time.',
  'review.follow_up_error': 'The review was saved, but some case card updates could not be saved.',
  'review.gate_blocked': 'The evidence requirement is not met yet.',
  'review.run_failed': 'The review could not be completed. Nothing was saved. {error}',
  'review.differences.card': 'Case card',
  'review.differences.form': 'Form',
  'review.later_count': '{n}',
  'pf.corr.add_marked': 'Add marked-up pages',
  'pf.corr.add_corrected': 'Add corrected pages',
  'pf.corr.check': '{form} p.{page} has {field} {corrected}. The markup seems to say {markup}.',
  'pf.corr.unreadable': '{form} p.{page}: the handwritten {field} could not be read clearly. Check it against {corrected} by hand.',
  'pf.corr.tag.check': 'Check',
  'pf.corr.tag.unreadable': 'Unreadable',
  'pf.corr.sent': '{n} corrected value(s) proposed to the case card for review.',
  'ps.files_heading': 'Package',
  'ps.drop.meta': 'The printed package, scanned. Forms and evidence together.',

  // ── Sign-off (D-75) ──
  'signoff.saving': 'Saving…',
  'signoff.error': 'The sign-off was not saved: {error}',

  // ── Email (D-61) ──
  'email.hint': 'Off unless turned on. Sends only the stage result and a link to the report, to the firm notification address.',
  'email.sent': 'Emailed to the firm notification address.',
  'email.not_sent': 'The review was saved, but the email was not sent.',
  'email.no_address': 'No firm notification address is set, so nothing was emailed.',

  // ── Full case cards (D-100) ──
  'field.uscis_account_number': 'USCIS online account number',
  'field.country_of_birth': 'Country of birth',
  'field.country_of_citizenship': 'Country of citizenship',
  'field.i94_number': 'I-94 number',
  'field.i94_expiration': 'I-94 expires',
  'field.last_entry_date': 'Last entry',
  'field.port_of_entry': 'Port of entry',
  'field.employer': 'Employer',
  'field.marriage_date': 'Date of marriage',
  'field.marriage_place': 'Place of marriage',
  'field_in.uscis_account_number': 'USCIS online account number',
  'field_in.country_of_birth': 'country of birth',
  'field_in.country_of_citizenship': 'country of citizenship',
  'field_in.i94_number': 'I-94 number',
  'field_in.i94_expiration': 'I-94 expiration date',
  'field_in.last_entry_date': 'last entry date',
  'field_in.port_of_entry': 'port of entry',
  'field_in.employer': 'employer',
  'field_in.marriage_place': 'place of marriage',
  'field_in.expiration_date': 'expiration date',
  'ez.fact.uscis_account_number': 'USCIS account',
  'ez.fact.country_of_birth': 'Born in',
  'ez.fact.country_of_citizenship': 'Citizen of',
  'ez.fact.i94_number': 'I-94 number',
  'ez.fact.i94_expiration': 'I-94 expires',
  'ez.fact.last_entry_date': 'Last entry',
  'ez.fact.port_of_entry': 'Port of entry',
  'ez.fact.employer': 'Employer',
  'ez.fact.marriage_place': 'Place of marriage',
  'ez.fact.expiration_date': 'Document expires',
  'ref.group.immigration': 'Immigration',
  'ref.group.work': 'Work',
  'ref.group.marriage': 'Marriage',
  'ez.type.passport': 'Passport',
  'ez.type.i94': 'I-94',
  'ez.type.green_card': 'Green card',

  // ── Forms found in this package (D-100 #3) ──
  'forms.heading': 'Forms found in this package',
  'forms.note': 'For information. Not counted, and no list of required forms.',
  'forms.pages': 'pages {pages}',
  'forms.no_person': 'Not about one person',

  // ── Possible issues (D-59, D-60) ──
  'pi.heading': 'Possible issues',
  'pi.accept': 'Accept',
  'pi.accepted': 'Accepted. Noted for this case only; the count and the report state are unchanged.',
  'pi.dismiss': 'Dismiss',
  'pi.dismiss_reasons': 'Reason for dismissing',
  'pi.suggest': 'Suggest as a future rule',
  'pi.saving': 'Saving…',
  'pi.failed': 'That did not save: {error}',
  'pi.why': 'Why it matters',
  'pi.uncertainty': 'What is uncertain',
  'pi.evidence': 'Where',
  'pi.not_stored': 'This review was not saved, so these cannot be decided.',
  'suggest.scope.case': 'This case type ({case_type})',
  'suggest.scope.recommended': 'Choose the scope. Staff can edit the rule later in the Rulebook.',

  // ── Rulebook (D-61, D-65, D-76) ──
  'rulebook.sub': 'Firm-wide rules apply to every case type. Case-type rules add to them. A change affects future reviews only.',
  'rulebook.case_type': 'Case type',
  'rulebook.retire': 'Retire',
  'rulebook.retire_confirm': 'Retire this rule? Later reviews will not check it.',
  'rulebook.retire_yes': 'Retire rule',
  'rulebook.origin.possible_issue': 'Suggested from a possible issue',
  'rulebook.origin.staff_added': 'Added by staff',
  'rulebook.origin.firm_decision': 'Firm decision',
  'rulebook.origin.staff': 'Added by staff',
  'rulebook.version': 'Rule set version {n}',
  'rulebook.saved': 'Saved. Affects future reviews only.',
  'rulebook.none': 'No rules here yet.',
  'rulebook.firm.none': 'No firm-wide rules.',
};
